/// GERMAN TRANSLATIONS
/// Same keys as English, translated to German.
class AppLocalizationsDe {
  static const Map<String, String> strings = {
    // ──── GENERAL ────
    'appTitle': 'Vybin',
    'loading': 'Laden...',
    'error': 'Fehler',
    'noInternet': 'Keine Internetverbindung!',
    'retry': 'Wiederholen',
    'cancel': 'Abbrechen',
    'save': 'Speichern',
    'delete': 'Löschen',
    'confirm': 'Bestätigen',
    'ok': 'OK',
    'submit': 'Absenden',
    'update': 'Aktualisieren',
    'done': 'Fertig',
    'skip': 'Überspringen',
    'description': 'Beschreibung',
    'settings': 'Einstellungen',
    'search': 'Suchen...',
    'searchForEvents': 'Nach Veranstaltungen suchen',
    'searchForCommunities': 'Nach Communities suchen',
    'searchConversation': 'Unterhaltung suchen',
    'allVibes': 'Alle Vibes',
    'otherVibes': 'Andere Vibes',
    'viewOnMap': 'Auf Karte anzeigen',
    'create': 'Erstellen',
    'expiresIn': 'Läuft ab in',
    'expired': 'Abgelaufen',
    'lessThan1m': 'Weniger als 1m',
    'addNewCategory': 'Neue Kategorie hinzufügen',
    'addSubCategory': 'Unterkategorie hinzufügen',
    'uploadCoverImage': 'Titelbild hochladen',
    'clickToBrowse': 'Zum Durchsuchen klicken',
    'selectAddress': 'Adresse auswählen',
    'select': 'Auswählen',
    'eventDateTime': 'Datum & Uhrzeit',
    'startingDate': 'Startdatum',
    'startingTime': 'Startzeit',
    'endingDate': 'Enddatum',
    'endingTime': 'Endzeit',
    'selectedLocation': 'Ausgewählter Ort',
    'privacyFirst': 'Datenschutz zuerst',
    'privacyFirstDesc':
        'Ihr genauer Standort wird nur mit Personen geteilt, denen Sie zuwinken und die Sie akzeptieren',
    'organized': 'Organisiert',
    'close': 'Schließen',
    'back': 'Zurück',
    'next': 'Weiter',
    'edit': 'Bearbeiten',
    'send': 'Senden',
    'clear': 'Löschen',
    'tapAgainToExit': 'Nochmal tippen zum Beenden',
    'noItemsFound': 'Keine Einträge gefunden',
    'noResultsMatchSearch': 'Keine Ergebnisse gefunden',
    'clearSearch': 'Suche löschen',
    'share': 'Teilen',
    'report': 'Melden',
    'block': 'Blockieren',
    'requestSent': 'Anfrage gesendet',
    'invitationSent': 'Einladung gesendet',
    'processing': 'Verarbeitung...',
    'success': 'Erfolg',
    'failed': 'Fehlgeschlagen',
    'warning': 'Warnung',
    'info': 'Info',
    'saving': 'Speichern...',
    'selectDate': 'Datum auswählen',
    'networkError': 'Netzwerkfehler. Bitte versuchen Sie es erneut.',
    'somethingWentWrong':
        'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
    'pleaseWait': 'Bitte warten...',

    // ──── AUTH ────
    'signIn': 'Anmelden',
    'signUp': 'Registrieren',
    'signInToAccount': 'Melden Sie sich in Ihrem Konto an',
    'createAccount': 'Konto erstellen',
    'email': 'E-Mail',
    'enterEmail': 'E-Mail-Adresse eingeben',
    'password': 'Passwort',
    'enterPassword': 'Passwort eingeben',
    'confirmPassword': 'Passwort bestätigen',
    'name': 'Name',
    'enterName': 'Name eingeben',
    'forgotPassword': 'Passwort vergessen?',
    'rememberMe': 'Angemeldet bleiben',
    'dontHaveAccount': 'Noch kein Konto? ',
    'alreadyHaveAccount': 'Bereits ein Konto? ',
    'logOut': 'Abmelden',
    'areYouSureLogOut': 'Möchten Sie sich wirklich abmelden?',
    'otpVerification': 'OTP-Verifizierung',
    'verify': 'Verifizieren',
    'resend': 'Erneut senden',
    'resendCode': 'Code erneut senden',
    'resetPassword': 'Passwort zurücksetzen',
    'sendOtp': 'OTP senden',
    'congratulations': 'Glückwunsch!',
    'enterOtp': 'Geben Sie den OTP-Code ein, der an Ihre E-Mail gesendet wurde',
    'newPassword': 'Neues Passwort',
    'enterNewPassword': 'Neues Passwort eingeben',
    'passwordChanged': 'Passwort erfolgreich geändert',
    'accountCreated': 'Konto erfolgreich erstellt',
    'otpVerified': 'OTP erfolgreich verifiziert.',
    'otpResent': 'OTP erneut gesendet',
    'loginSuccessful': 'Anmeldung erfolgreich',
    'emailSent': 'E-Mail erfolgreich gesendet',
    'emailVerification': 'E-Mail-Verifizierung',
    'pleaseEnterEmail': 'Bitte geben Sie Ihre E-Mail-Adresse ein',
    'pleaseEnterValidEmail': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    'pleaseEnterPassword': 'Bitte geben Sie Ihr Passwort ein',
    'passwordMinLength': 'Das Passwort muss mindestens 6 Zeichen lang sein',
    'passwordsDoNotMatch': 'Passwörter stimmen nicht überein',
    'preferNotToSay': 'Keine Angabe',
    'setPassword': 'Passwort festlegen',

    // ──── ONBOARDING / INTRO ────
    'getStarted': 'Loslegen',
    'letsVibeTogether': 'Lass uns zusammen viben',
    'discoverVibesDesc': 'Entdecke Vibes in deiner Nähe',
    'spontaneousConnections': 'Knüpfe spontane echte Kontakte',
    'createOwnEvents': 'Erstelle deine eigenen Events',
    'createOwnCommunities': 'Erstelle deine eigenen Communities',
    'safePrivacyFirst': 'Sicher & datenschutzorientiert gestaltet',
    'letsConnect': 'Verbinden wir uns',
    'continueText': 'Weiter',
    'chooseLanguage': 'Sprache wählen',
    'selectPreferredLanguage': 'Wählen Sie Ihre bevorzugte Sprache',
    'stepName': 'Wie ist Ihr Name?',
    'stepPhoto': 'Laden Sie Ihr Foto hoch',
    'stepInterests': 'Wählen Sie Ihre Interessen',
    'stepLocation': 'Standort festlegen',
    'stepGender': 'Geschlecht auswählen',
    'stepBirthday': 'Wann ist Ihr Geburtstag?',
    'stepBirthdaySubtitle':
        'Ihr Profil zeigt nur Ihr Alter, nie Ihr volles Geburtsdatum.',
    'stepLookingFor': 'Was suchen Sie?',
    'male': 'Männlich',
    'female': 'Weiblich',
    'other': 'Andere',
    'uploadPhoto': 'Foto hochladen',
    'takePhoto': 'Foto aufnehmen',
    'chooseFromGallery': 'Aus Galerie wählen',
    'enterYourName': 'Geben Sie Ihren Namen ein',
    'selectInterests': 'Interessen auswählen',
    'setLocation': 'Standort festlegen',
    'currentLocation': 'Aktueller Standort',
    'welcomeTo': 'Willkommen bei Vybin',

    // ──── HOME ────
    'home': 'Start',
    'explore': 'Entdecken',
    'profile': 'Profil',
    'events': 'Veranstaltungen',
    'communities': 'Communities',
    'vibes': 'Vibes',
    'chat': 'Chat',
    'waves': 'Wellen',
    'nearby': 'In der Nähe',
    'seeAll': 'Alle anzeigen',
    'discover': 'Entdecken',
    'map': 'Karte',
    'filter': 'Filter',
    'all': 'Alle',
    'myEvents': 'Meine Veranstaltungen',
    'myCommunities': 'Meine Communities',
    'joined': 'Teilgenommen',
    'requested': 'Angefragt',
    'popular': 'Beliebt',
    'recent': 'Kürzlich',
    'distance': 'Entfernung',
    'km': 'km',
    'mi': 'mi',
    'people': 'Leute',
    'attending': 'Teilnehmend',
    'interested': 'Interessiert',
    'maxAttendees': 'Max. Teilnehmer',
    'noEvents': 'Keine Veranstaltungen gefunden',
    'noCommunities': 'Keine Communities gefunden',
    'noVibes': 'Keine Vibes verfügbar',

    // ──── EVENTS ────
    'createEvent': 'Veranstaltung erstellen',
    'editEvent': 'Veranstaltung bearbeiten',
    'eventDetails': 'Veranstaltungsdetails',
    'eventTitle': 'Titel',
    'eventDate': 'Datum',
    'eventTime': 'Uhrzeit',
    'eventLocation': 'Ort',
    'eventCategory': 'Kategorie',
    'eventDescription': 'Beschreibung',
    'eventImage': 'Titelbild',
    'public': 'Öffentlich',
    'private': 'Privat',
    'accessLevel': 'Zugriffslevel',
    'joinEvent': 'Teilnehmen',
    'leaveEvent': 'Verlassen',
    'interestedEvent': 'Interessiert',
    'eventJoined': 'Erfolgreich beigetreten',
    'eventLeft': 'Veranstaltung verlassen',
    'eventDeleted': 'Veranstaltung gelöscht',
    'eventCreated': 'Veranstaltung erstellt',
    'eventUpdated': 'Veranstaltung aktualisiert',
    'eventCheckin': 'Einchecken',
    'eventCheckout': 'Auschecken',
    'eventMembers': 'Mitglieder',
    'eventRequests': 'Anfragen',
    'eventHost': 'Veranstaltet von',
    'eventStart': 'Beginn',
    'eventEnd': 'Ende',
    'eventCapacity': 'Kapazität',
    'eventFull': 'Veranstaltung ist voll',
    'eventPrivate': 'Dies ist eine private Veranstaltung',
    'requestToJoin': 'Teilnahme anfragen',
    'withdrawRequest': 'Anfrage zurückziehen',
    'scanQR': 'QR-Code scannen',
    'showMyQR': 'Meinen QR-Code zeigen',
    'removeMember': 'Entfernen',
    'approve': 'Genehmigen',
    'reject': 'Ablehnen',
    'eventOrCommunity': 'Was möchten Sie erstellen?',

    // ──── COMMUNITIES ────
    'createCommunity': 'Community erstellen',
    'editCommunity': 'Community bearbeiten',
    'communityDetails': 'Community-Details',
    'communityTitle': 'Community-Titel',
    'communityDescription': 'Beschreibung',
    'communityRules': 'Regeln',
    'communityLocation': 'Standort',
    'communityDate': 'Datum',
    'communityTime': 'Uhrzeit',
    'communityCategory': 'Kategorie',
    'communityImage': 'Titelbild',
    'joinCommunity': 'Beitreten',
    'leaveCommunity': 'Verlassen',
    'interestedCommunity': 'Interessiert',
    'communityJoined': 'Erfolgreich beigetreten',
    'communityLeft': 'Community verlassen',
    'communityCreated': 'Community erstellt',
    'communityUpdated': 'Community aktualisiert',
    'communityMembers': 'Mitglieder',
    'communityRequests': 'Anfragen',
    'manageMembers': 'Mitglieder verwalten',
    'communityHost': 'Erstellt von',
    'communityCapacity': 'Kapazität',
    'communityFull': 'Community ist voll',
    'communityPrivate': 'Dies ist eine private Community',
    'requestToJoinCommunity': 'Beitritt anfragen',
    'scheduleMeetup': 'Treffen planen',
    'meetups': 'Treffen',
    'createMeetup': 'Treffen erstellen',
    'meetupDetails': 'Treffendetails',
    'meetupTitle': 'Treffentitel',
    'meetupDescription': 'Beschreibung',
    'meetupDate': 'Datum',
    'meetupTime': 'Uhrzeit',
    'meetupLocation': 'Ort',
    'meetupMembers': 'Teilnehmer',
    'joinMeetup': 'Teilnehmen',
    'meetupJoined': 'Treffen beigetreten',
    'inviteMembers': 'Mitglieder einladen',
    'invited': 'Eingeladen',
    'meetupCreated': 'Treffen erstellt',
    'awaitingApproval': 'Warten auf Genehmigung',
    'approved': 'Genehmigt',

    // ──── CHAT ────
    'chats': 'Chats',
    'messages': 'Nachrichten',
    'typeMessage': 'Nachricht eingeben...',
    'sendMessage': 'Senden',
    'voiceMessage': 'Sprachnachricht',
    'image': 'Bild',
    'photo': 'Foto',
    'gallery': 'Galerie',
    'camera': 'Kamera',
    'recordAudio': 'Audio aufnehmen',
    'stopRecording': 'Aufnahme beenden',
    'deleteMessage': 'Nachricht löschen',
    'editMessage': 'Nachricht bearbeiten',
    'copyMessage': 'Nachricht kopieren',
    'messageDeleted': 'Diese Nachricht wurde gelöscht',
    'messageEdited': '(bearbeitet)',
    'messageCopied': 'Kopiert',
    'areYouSureDelete': 'Möchten Sie diese Nachricht wirklich löschen?',
    'noMessages': 'Noch keine Nachrichten',
    'isTyping': 'tippt...',
    'online': 'Online',
    'offline': 'Offline',
    'eventChat': 'Veranstaltungschat',
    'communityChat': 'Community-Chat',
    'privateChat': 'Privater Chat',
    'chatList': 'Chat-Liste',
    'markAsRead': 'Als gelesen markieren',
    'unread': 'Ungelesen',

    // ──── VIBE / WAVE ────
    'vibe': 'Vibe',
    'createVibe': 'Vibe erstellen',
    'myVibe': 'Mein Vibe',
    'vibeTitle': 'Vibe-Titel',
    'vibeDuration': 'Dauer',
    'endVibe': 'Vibe beenden',
    'vibeEnded': 'Vibe beendet',
    'vibeCreated': 'Vibe erstellt',
    'sendWave': 'Welle senden',
    'waveSent': 'Welle gesendet!',
    'waveSendFailed': 'Welle konnte nicht gesendet werden',
    'acceptWave': 'Akzeptieren',
    'rejectWave': 'Ablehnen',
    'waveAccepted': 'Welle akzeptiert!',
    'waveRejected': 'Welle abgelehnt',
    'incomingWave': 'Eingehende Welle',
    'someoneWaved': 'Jemand hat Ihnen zugewunken!',
    'waveFrom': 'Welle von',
    'meetConfirm': 'Treffen bestätigen',
    'meetReschedule': 'Verschieben',
    'meetLocation': 'Ort vorschlagen',
    'suggestedLocation': 'Vorgeschlagener Ort',
    'confirmMeetup': 'Treffen bestätigen',
    'rescheduleMeetup': 'Treffen verschieben',
    'meetNow': 'Jetzt treffen',
    'activeVibes': 'Aktive Vibes',
    'noActiveVibes': 'Keine aktiven Vibes',

    // ──── PROFILE ────
    'myProfile': 'Mein Profil',
    'editProfile': 'Profil bearbeiten',
    'profilePhoto': 'Profilfoto',
    'bio': 'Bio',
    'enterBio': 'Bio eingeben',
    'interests': 'Interessen',
    'changePassword': 'Passwort ändern',
    'currentPassword': 'Aktuelles Passwort',
    'yourPhotos': 'Ihre Fotos',
    'likedProfiles': 'Gefallene Profile',
    'lockedProfile': 'Gesperrtes Profil',
    'profileLocked': 'Dieses Profil ist gesperrt',
    'unlockProfile': 'Profil entsperren',
    'trustScore': 'Vertrauenswert',
    'meets': 'Treffen',
    'lookingFor': 'Suche nach',

    // ──── SETTINGS ────
    'language': 'Sprache',
    'english': 'English',
    'german': 'Deutsch',
    'theme': 'thema',
    'light': 'Hell',
    'dark': 'Dunkel',
    'system': 'System',
    'themeMode': 'thema Modus',
    'notifications': 'Benachrichtigungen',
    'privacy': 'Datenschutz',
    'termsOfService': 'Nutzungsbedingungen',
    'privacyPolicy': 'Datenschutzerklärung',
    'about': 'Über',
    'version': 'Version',
    'account': 'Konto',
    'deleteAccount': 'Konto löschen',
    'areYouSureDeleteAccount': 'Möchten Sie Ihr Konto wirklich löschen?',
    'deleteReason': 'Bitte teilen Sie uns mit, warum Sie gehen',
    'accountDeleted': 'Konto gelöscht',
    'pauseProfile': 'Profil pausieren',
    'profilePaused': 'Profil pausiert',
    'managePassword': 'Passwort verwalten',
    'blockedAccounts': 'Blockierte Konten',
    'noBlockedAccounts': 'Keine blockierten Konten',
    'help': 'Hilfe',
    'appInfo': 'App-Info',
    'logout': 'Abmelden',
    'loggedOut': 'Erfolgreich abgemeldet',

    // ──── SUBSCRIPTION ────
    'subscription': 'Abonnement',
    'subscribe': 'Abonnieren',
    'upgrade': 'Upgrade',
    'premium': 'Premium',
    'basic': 'Basis',
    'free': 'Kostenlos',
    'monthly': 'Monatlich',
    'yearly': 'Jährlich',
    'payment': 'Zahlung',
    'payNow': 'Jetzt bezahlen',
    'paymentSuccessful': 'Zahlung erfolgreich!',
    'paymentFailed': 'Zahlung fehlgeschlagen',
    'choosePlan': 'Wählen Sie Ihren Tarif',
    'currentPlan': 'Aktueller Tarif',

    // ──── QR ────
    'qrCode': 'QR-Code',
    'scanQRCode': 'QR-Code scannen',
    'myQRCode': 'Mein QR-Code',
    'qrScan': 'Scannen',
    'qrCodeFor': 'QR-Code für',
    'scanToJoin': 'Scannen zum Beitreten',
    'invalidQR': 'Ungültiger QR-Code',
    'qrScanned': 'QR-Code gescannt',
    'qrScannedSuccess': 'Sie haben sich erfolgreich verbunden!',
    'startChatting': 'Chat starten',

    // ──── ADDITIONAL UI STRINGS ────
    'searchDot': 'Suchen ...',
    'youAreInsideEvent': 'Sie sind in der Veranstaltung',
    'enjoyTheMoment': 'Genießen Sie den Moment!',
    'leaveEventZone': 'Veranstaltungszone verlassen',
    'leftEventZone': 'Veranstaltungszone verlassen',
    'leftEventDesc':
        'Sie haben die Veranstaltungszone verlassen. Rückkehr zur Karte...',
    'loadingEvent': 'Veranstaltung wird geladen...',
    'locationNotAvailable': 'Standort nicht verfügbar',
    'eventZone': 'Veranstaltungszone',
    'eventNotFound': 'Veranstaltung nicht gefunden',
    'viewAll': 'Alle anzeigen',
    'noParticipants': 'Noch keine Teilnehmer',
    'noPendingRequests': 'Keine ausstehenden Anfragen',
    'noAwaitingMembers': 'Keine wartenden Mitglieder',
    'accept': 'Akzeptieren',
    'participants': 'Teilnehmer',
    'manageRequest': 'Anfragen verwalten',
    'pending': 'Ausstehend',
    'awaitingMeetup': 'Warten auf Treffen',
    'viewQR': 'QR anzeigen',
    'scanQRCodeToVerify': 'QR-Code scannen',
    'aboutCommunity': 'Über die Community',
    'planedMeetup': 'Geplante Treffen',
    'noMeetupsPlanned': 'Noch keine Treffen geplant',
    'planMeetup': 'Treffen planen',
    'leave': 'Verlassen',
    'viewOnMapBtn': 'Auf Karte anzeigen',
    'endVibeEarly': 'Vibe vorzeitig beenden?',
    'endVibeDesc': 'Ihr Vibe verschwindet sofort von der Karte',
    'endNow': 'Jetzt beenden',
    'noActiveVibe': 'Kein aktiver Vibe gefunden.',
    'noOtherVibes': 'Keine anderen Vibes gefunden.',
    'vibeDurationLeft': 'übrig',
    'statusLive': 'LIVE',
    'noTitle': 'Kein Titel',
    'waved': 'Gewunken',
    'wave': 'Winken',
    'itsAVibe': 'Es ist ein Vibe',
    'youBothWantToConnect': 'Ihr wollt euch beide verbinden!',
    'suggestMeetingSpot': 'Treffpunkt vorschlagen',
    'cancelMeetup': 'Treffen absagen',
    'greatSeeYouSoon': 'Großartig, bis bald!',
    'meetAtMyLocation': 'An meinem Standort treffen',
    'hereAndNow': 'Hier und jetzt',
    'suggestMidpoint': 'Mittelpunkt vorschlagen',
    'pickLocationOnMap': 'Ort auf Karte auswählen',
    'later': 'Später',
    'scheduleMeetupConfirm': 'Vereinbaren Sie ein Treffen zur Verifizierung',
    'scheduleQRDesc':
        'Sie müssen Ihren QR-Code scannen, um der Community beizutreten.',
    'qrMustBeScanned':
        'QR-Code muss persönlich gescannt werden, um Mitglied zu werden',
    'cancelMeetupAnytime': 'Sie können dieses Treffen jederzeit absagen',
    'youreOfficialMember': 'Sie sind jetzt offizielles Mitglied,',
    'feelFreeToSayHi': 'Sagen Sie gerne Hallo in der Gruppe',
    'enterCommunity': 'Community betreten',
    'members': 'Mitglieder',
    'pendingMeetupsNote':
        'Nicht abgeschlossene Treffen können Ihren Respekt-Score beeinflussen.',
    'trustEcosystem': 'Dies verbindet Communities mit Ihrem Trust-Ökosystem.',
    'unblock': 'Entblocken',
    'unblockSuccess': 'Benutzer erfolgreich entblockt',
    'unblockFailed': 'Entblocken fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'areYouSureUnblock':
        'Sind Sie sicher, dass Sie {userName} entblocken möchten?',
    'whatHappened': 'Was ist passiert?',
    'blockDescription': 'Teilen Sie uns mit, warum Sie diesen Benutzer blockieren möchten. Er wird nicht benachrichtigt.',
    'blockSuccess': 'Sie haben {userName} blockiert. Sie werden keine Benachrichtigungen von diesem Benutzer erhalten.',
    'blockFailed': 'Blockieren fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'explainHere': 'Hier erklären...',
    'activeMembers': 'Aktive Mitglieder',
    'invitedMembers': 'Eingeladene Mitglieder',
    'mute': 'Stumm',
    'deleteChat': 'Chat löschen',
    'blockUser': 'Benutzer blockieren',
    'onlyCreatorCanSend': 'Nur der Veranstalter kann Nachrichten senden',
    'editingMessage': 'Nachricht bearbeiten',
    'sentAFile': 'Hat eine Datei gesendet',
    'addACaption': 'Bildunterschrift hinzufügen...',
    'wantsToMeetYou': 'möchte Sie treffen.',
    'acceptToSuggest':
        'Akzeptieren, um einen Ort und Zeit für ein kurzes Treffen vorzuschlagen',
    'youHaveRejected': 'Sie haben',
    'waveRequest': 'Wellenanfrage abgelehnt.',
    'youHaveReported': 'Sie haben',
    'youWillNotReceive':
        'Sie werden keine Benachrichtigungen von diesem Benutzer erhalten.',
    'youHaveBlocked': 'Sie haben',
    'awaitingQR': 'Warten auf QR',
    'hasBeenApproved': 'wurde genehmigt!',
    'confirmPasswordToProceed':
        'Aus Sicherheitsgründen bestätigen Sie bitte Ihr Passwort.',
    'giveReason':
        'Geben Sie uns einen Grund, warum Sie das Konto pausieren möchten',
    'reason': 'Grund',
    'accountInformation': 'Kontoinformationen',
    'changeYourPassword': 'Passwort ändern',
    'pauseYourAccount': 'Konto pausieren',
    'deleteYourAccount': 'Konto löschen',
    'deleteConfirmation': 'Löschbestätigung',
    'deleteAccountDesc':
        'Sie können Ihr Konto löschen, aber der Vorgang kann einige Zeit dauern. Nach dem Löschen kann es nicht wiederhergestellt werden.',
    'profileCompletion': 'Profilvollständigkeit',
    'selectUpTo5': 'Interessen (maximal 5 auswählen)',
    'max5Interests': 'Sie können maximal 5 Interessen auswählen',
    'profileUpdated': 'Profil erfolgreich aktualisiert',
    'passwordUpdated': 'Passwort erfolgreich aktualisiert',
    'updatePassword': 'Passwort aktualisieren',
    'uploading': 'Aktualisieren...',
    'newCategory': 'Neue Kategorie hinzufügen',
    'addCategory': 'Hinzufügen',
    'enterCategoryName': 'Kategoriename eingeben',
    'membersCount': 'Mitglieder (24)',
    'youAreAdmin': 'Sie sind ein Admin',
    'pendingMeetups':
        'Nicht abgeschlossene Treffen können Ihren Respekt-Score beeinflussen. Dies verbindet Communities mit Ihrem Trust-Ökosystem.',
    'eventRequestSent': 'Anfrage gesendet',
    'yourRequestHasBeenSent': 'Ihre Anfrage wurde gesendet!',
    'withdrawing': 'Wird zurückgezogen...',
    'eventAccessGranted': 'Zugriff gewährt',
    'qrCodeDescription':
        'Denken Sie daran, bei der Ankunft den QR-Code zu scannen',
    'createSomethingNew': 'Etwas Neues erstellen',
    'startEventOrCommunity':
        'Starten Sie eine Veranstaltung oder bauen Sie eine Community auf.',
    'eventCategoryLabel': 'Veranstaltungskategorie',
    'communityCategoryLabel': 'Community-Kategorie',
    'selectLocation': 'Standort auswählen',
    'profileCompletionLabel': 'Profilvollständigkeit',
    'noBioYet': 'Noch keine Bio',
    'locationNotSet': 'Standort nicht festgelegt',
    'enterYourBio':
        'Geben Sie hier Ihre Bio ein. Sie wird für Ihre Freunde sichtbar sein.',
    'addInterestCategory': 'Interessenkategorie hinzufügen',
    'enterInterestName': 'Interessenname eingeben',
    'addSubInterest': 'Unterinteresse hinzufügen',
    'areYouSureDeletePhoto': 'Möchten Sie dieses Foto wirklich löschen?',
    'photoAdded': 'Foto erfolgreich hinzugefügt',
    'failedToUpload':
        'Foto konnte nicht hochgeladen werden. Bitte versuchen Sie es erneut.',
    'showQRCode': 'QR-Code anzeigen',
    'showQRToVerify': 'Zeigen Sie diesen QR-Code zur Verifikation des Treffens',
    'enterYourLocation': 'Standort eingeben',
    'searchInterestHint': 'Tippen, um weitere Interessen zu finden\u2026',
    'noInterestAddedYet': 'Noch keine Interessen hinzugefügt',
    'noResultsFound': 'Keine Ergebnisse gefunden',
    'interestUpdateSuccess': 'Interessen erfolgreich aktualisiert',
    'interestUpdateFailed': 'Interessen konnten nicht aktualisiert werden',
    'maxInterestSelection': 'Sie können maximal {count} Interessen auswählen',
    'profilePhotoUpdated': 'Profilfoto aktualisiert',
    'failedToUpdatePhoto': 'Profilfoto konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.',
    'changePhoto': 'Ändern',
    'failedToPickImage': 'Bild konnte nicht ausgewählt werden',
    'updateEvent': 'Aktualisieren',
    'updateEventConfirm':
        'Die Aktualisierung benachrichtigt alle Teilnehmer.\\nSind Sie sicher?',
    'deleteEventConfirm': 'Möchten Sie es wirklich löschen?',
    'archiveConfirm': 'Möchten Sie es wirklich archivieren?',
    'yes': 'Ja',
    'youDeletedEvent': 'Sie haben die Veranstaltung gelöscht',
    'communityInfo': 'Community-Info',
    'selectDateAndTimeFirst': 'Wählen Sie zuerst Datum und Uhrzeit',
    'noParticipantsYet': 'Noch keine Teilnehmer',
    'noInvitedMembers': 'Noch keine eingeladenen Mitglieder',
    'noMembersFound': 'Keine Mitglieder gefunden',
    'photoAddedSuccess': 'Foto erfolgreich hinzugefügt',
    'updating': 'Aktualisieren...',
    'invalidCommunity': 'Ungültige Community',
    'communityUpdatedSuccess': 'Community erfolgreich aktualisiert',
    'failedToUpdateCommunity': 'Community konnte nicht aktualisiert werden',
    'sundayCoffeeVibes': 'Sonntag Kaffee Vibes',
    'termsAndPrivacy': 'Nutzungsbedingungen und Datenschutz',
    'passwordMinLengthError':
        'Das Passwort muss mindestens 6 Zeichen lang sein',
    'passwordsDoNotMatchError': 'Passwörter stimmen nicht überein',

    // ──── NEW KEYS ────
    'defaultUserName': 'Benutzer',
    'myLocation': 'Mein Standort',
    'scanChatQR': 'Scannen Sie einen Chat-QR-Code zum Verbinden',
    'scanCommunityQR': 'Scannen Sie einen Community-QR-Code zum Beitreten',
    'scanEventQR': 'Scannen Sie einen Event-QR-Code zum Einchecken',
    'scanName': 'Scannen',
    'paymentMethod': 'Zahlungsmethode',
    'paypal': 'PayPal',
    'stripe': 'Stripe',
    'yourPaymentSuccessful': 'Ihre Zahlung wurde erfolgreich durchgeführt',
    'upgradePlan': 'Tarif upgraden',
    'mostPopular': 'Am beliebtesten',
    'perMonth': '/Monat',
    'selectMonth': 'Monat auswählen',
    'subscriptionFree': 'Kostenlos',
    'plans': 'Tarife',
    'getStartedWithLocalDiscovery': 'Starten Sie mit lokaler Erkundung',
    'forActiveMembers': 'Für aktive Community-Mitglieder',
    'forOrganizers': 'Für Organisatoren und Power-User',
    'private_tab': 'Privat',
    'wavesPerDay': 'Wellen / Tag',
    'unlimitedVibes': 'Unbegrenzte Vibes',
    'joinUpTo': 'Treten Sie bis zu',
    'communitiesCount': 'Communities bei',
    'createUpTo': 'Erstellen Sie bis zu',
    'membersPerCommunity': 'Mitglieder / Community',
    'eventsPerMonth': 'Veranstaltungen / Monat',
    'participantsPerEvent': 'Teilnehmer / Veranstaltung',
    'wavedYou': 'Hat dir gewunken',
    'wavedAt': 'Welle gesendet bei',
    'unlimitedWaves': 'Unbegrenzte Wellen',
    'unlimitedCommunities': 'Unbegrenzte Communities',
    'createUpToCommunities': 'Erstellen Sie bis zu',
    'unlimitedMembers': 'Unbegrenzte Mitglieder',
    'joinEventsNoLimit':
        'Nehmen Sie an Veranstaltungen ohne Entfernungsbegrenzung teil',
    'createUnlimitedEvents': 'Erstellen Sie unbegrenzte Veranstaltungen',
    'unlimitedParticipants': 'Unbegrenzte Teilnehmer',
    'maxImages': 'Maximale Anzahl an Bildern',
    'reportSpam': 'Spam oder Fehlinformationen',
    'reportHateSpeech': 'Hassreden oder Gewalt',
    'reportThreats': 'Drohungen oder Belästigung',
    'reportHint': 'Geben Sie eine kurze Beschreibung ...',
    'others': 'Andere',
    'proTip': 'Profi-Tipp',
    'gotIt': 'Verstanden!',
    'eventOption': 'Veranstaltung',
    'communityOption': 'Community',
    'eventOptionDesc':
        'Organisieren Sie Treffen oder besondere Anlässe, die Menschen zusammenbringen',
    'communityOptionDesc':
        'Schaffen Sie einen Raum, in dem Menschen mit gemeinsamen Interessen sich vernetzen und wachsen können',
    'proTipDesc':
        'Communities sind für langfristige Verbindungen, Events für bestimmte Anlässe und Vibes für flüchtige Momente.',

    // ──── TIME / DATE ────
    'jan': 'Jan',
    'feb': 'Feb',
    'mar': 'Mär',
    'apr': 'Apr',
    'may': 'Mai',
    'jun': 'Jun',
    'jul': 'Jul',
    'aug': 'Aug',
    'sep': 'Sep',
    'oct': 'Okt',
    'nov': 'Nov',
    'dec': 'Dez',
    'justNow': 'gerade eben',
    'minAgo': 'Min. vergangen',
    'hourAgo': 'Stunde vergangen',
    'hoursAgo': 'Stunden vergangen',
    'yesterday': 'gestern',
    'am': 'AM',
    'pm': 'PM',

    // ──── COMMUNITY MEMBER SCREEN ────
    'activeTab': 'Aktiv',
    'requestedTab': 'Angefragt',
    'manage': 'Verwalten',
    'noActiveMembers': 'Noch keine aktiven Mitglieder',
    'requestedToJoin': 'Beitritt angefragt',
    'youHaveAcceptedJoinRequest': 'Sie haben ',
    'youHaveRejectedJoinRequest': 'Sie haben ',
    'sJoinRequest': 's Community-Beitrittsanfrage angenommen.',
    'sJoinRequestRejected': 's Community-Beitrittsanfrage abgelehnt.',
    'failedToAccept': 'Anfrage konnte nicht akzeptiert werden.',
    'failedToReject': 'Anfrage konnte nicht abgelehnt werden.',

    // ──── MEETUP MEMBER SCREEN ────
    'participantsTab': 'Teilnehmer',
    'invitedTab': 'Eingeladen',
    'unknown': 'Unbekannt',
    'joinedAgo': 'Beigetreten ',
    'invitedAgo': 'Eingeladen ',

    // ──── PLAN FEATURES ────
    'planFreeWaveCount': '6 Wellen / Tag',
    'planFreeUnlimitedVibes': 'Unbegrenzte Vibes',
    'planFreeJoinCommunities': 'Treten Sie bis zu 3 Communities bei',
    'planFreeCreateCommunity': 'Erstellen Sie 1 Community',
    'planFreeMembersPerCommunity': 'Bis zu 25 Mitglieder / Community',
    'planFreeEventRange': 'Nehmen Sie an Events innerhalb von 200 km teil',
    'planFreeCreateEvent': 'Erstellen Sie 1 Event / Monat',
    'planPlusWaveCount': '12 Wellen / Tag',
    'planPlusUnlimitedVibes': 'Unbegrenzte Vibes',
    'planPlusJoinCommunities': 'Treten Sie bis zu 6 Communities bei',
    'planPlusCreateCommunities': 'Erstellen Sie bis zu 3 Communities',
    'planPlusMembersPerCommunity': 'Bis zu 50 Mitglieder / Community',
    'planPlusCreateEvents': 'Erstellen Sie 4 Events / Monat',
    'planPlusParticipantsPerEvent': 'Bis zu 100 Teilnehmer / Event',
    'planPremiumUnlimitedWaves': 'Unbegrenzte Wellen',
    'planPremiumUnlimitedVibes': 'Unbegrenzte Vibes',
    'planPremiumJoinUnlimitedCommunities':
        'Treten Sie unbegrenzten Communities bei',
    'planPremiumCreateCommunities': 'Erstellen Sie bis zu 6 Communities',
    'planPremiumUnlimitedMembers': 'Unbegrenzte Mitglieder / Community',
    'planPremiumJoinEventsNoLimit':
        'Nehmen Sie an Events ohne Entfernungsbegrenzung teil',
    'planPremiumCreateUnlimitedEvents': 'Erstellen Sie unbegrenzte Events',
    'planPremiumUnlimitedParticipants': 'Unbegrenzte Teilnehmer / Event',

    // ──── INTERESTS ────
    'interestCoffee': 'Kaffee',
    'interestMusic': 'Musik',
    'interestBooks': 'Bücher',
    'interestGaming': 'Gaming',
    'interestCalendar': 'Kalender',
    'interestTravel': 'Reisen',
    'interestFitness': 'Fitness',
    'interestCooking': 'Kochen',
    'interestArt': 'Kunst',
    'interestPhotography': 'Fotografie',

    // ──── PROFILE ────
    'defaultBio':
        'Kaffeeliebhaber. Musikliebhaber. Vielreisender. Feinschmecker.',

    // ──── MISSING KEYS ────
    'youLeft': 'Sie haben ',
    'going': 'teilnehmen',

    // ──── SETTINGS SCREEN ────
    'locationSharing': 'Standortfreigabe',
    'locationSharingDesc': 'Nur aktiv während Vibes',
    'blocked': 'Blockiert',
    'appSetting': 'App-Einstellung',
    'community': 'Community',

    // ──── LOCALIZATION GAPS ────
    'away': 'entfernt',
    'notNow': 'Jetzt nicht',
    'allow': 'Erlauben',
    'locationAccess': 'Standortzugriff',
    'locationAccessDesc':
        'Wird verwendet, um Sie mit dem zu verbinden, was in der Nähe ist.',
    'locationAccessSubtitle': 'Nur während der Nutzung der App.',
    'sendInvitation': 'Einladung senden',
    'inviteMembersToMeetup': 'Mitglieder zum Treffen einladen',
    'selectedMembersWillReceive':
        'Ausgewählte Mitglieder erhalten eine Einladung zur Teilnahme.',
    'invitedAll': 'Alle eingeladen',
    'member': 'Mitglied',
    'awaiting': 'Wartend',
    'scheduledMeetup': 'Geplantes Treffen',
    'location': 'Standort',
    'statusPendingApproval': 'Status: Ausstehende Genehmigung',
    'invitedToRealLifeMeetup':
        'Sie werden zu einem persönlichen Treffen eingeladen, bevor Sie Mitglied werden.',
    'youJoinedTheMeetup': 'Sie sind dem Treffen beigetreten!',
    'communityNotifications': 'Community-Benachrichtigungen',
    'event_tab': 'Event',
    'eventNotifications': 'Veranstaltungsbenachrichtigungen',
    'qrVerification': 'QR-Verifizierung',
    'qrTab': 'QR-Code',
    'scanTab': 'Scannen',
    'scanTheirQRCode': 'QR-Code scannen',
    'alignQRCode': 'QR-Code im Rahmen ausrichten',
    'cameraPermissionRequired': 'Kameraerlaubnis erforderlich',
    'uniqueQRCode': 'Dieser Code ist für diese Verbindung einzigartig',
    'qrInfoCommunity':
        'Scannen Sie diesen QR-Code, um einer Community beizutreten oder sich mit anderen Mitgliedern zu verbinden.',
    'qrInfoEvent':
        'Scannen Sie diesen QR-Code für Veranstaltungszugang oder -verifizierung.',
    'qrInfoChats':
        'Scannen Sie diesen QR-Code, um eine direkte persönliche Verbindung herzustellen.',
    'qrTitleCommunity': 'Einer Community beitreten',
    'qrTitleEvent': 'Veranstaltungszugang & Verifizierung',
    'qrTitleChats': 'Mit Chats verbinden',
    'qrSubtitleCommunity':
        'Lassen Sie andere diesen Code scannen, um der Community beizutreten',
    'qrSubtitleEvent':
        'Zeigen Sie diesen Code für den Veranstaltungseintritt vor',
    'qrSubtitleChats': 'Lassen Sie sie scannen, um sich sofort zu verbinden',
    'qrScanCommunity': 'Scannen Sie den QR-Code, um der Community beizutreten.',
    'qrScanEvent':
        'Scannen Sie den QR-Code, um sicher auf die Veranstaltung zuzugreifen.',
    'qrScanChats':
        'Scannen Sie den QR-Code, um sich sofort über den Chat zu verbinden.',
    'history': 'Verlauf',
    'clearAll': 'Alle löschen',
    'eventPublicDesc': 'Jeder kann diese Veranstaltung entdecken und ohne Genehmigung sofort beitreten.',
    'eventPrivateDesc': 'Personen benötigen Ihre Genehmigung, bevor sie dieser Veranstaltung beitreten können.',
    'respectScore': 'Respekt-Score',
    'trusted': 'Vertrauenswürdig',
    'noRealLifeMeets': 'Noch keine persönlichen Treffen',
    'basedOnMeets': 'Basierend auf ',
    'realLifeMeets': 'persönlichen Treffen',
    'youHaveAcceptedRequestDesc': 'Sie haben die Community-Beitrittsanfrage angenommen.',

    // ──── MEETUP / WAVE FLOW ────
    'locationSelected': '✓ Ausgewählt',
    'midpoint': 'Mittelpunkt',
    'failedToSuggestMeetup': 'Treffen konnte nicht vorgeschlagen werden',
    'pleaseSelectDateAndTime': 'Bitte Datum und Uhrzeit auswählen',
    'pleaseSelectLocation': 'Bitte wählen Sie einen Ort',
    'meetupRescheduled': 'Treffen erfolgreich verschoben',
    'failedToReschedule': 'Verschieben fehlgeschlagen',
    'failedToAcceptWave': 'Wellenanfrage konnte nicht angenommen werden',
    'youHaveRejectedWave': 'Sie haben {name} Wellenanfrage abgelehnt.',
    'invalidWaveData': 'Ungültige Wellendaten',
    'seeYouAt': 'Wir sehen uns bei {address}',
    'seeYouSoon': 'Bis bald!',
    'scheduledAt': 'Geplant für',

    // ──── BLOCKED CHAT ────
    'youBlockedThisUser': 'Sie haben diesen Benutzer blockiert. Entblocken Sie ihn, um Nachrichten zu senden.',
    'youHaveBeenBlocked': 'Sie wurden von diesem Benutzer blockiert.',
  };
}
