/// ENGLISH TRANSLATIONS
/// This is the SOURCE file. All other languages must have the
/// same keys with translated values.
class AppLocalizationsEn {
  static const Map<String, String> strings = {
    // ──── GENERAL ────
    'appTitle': 'Vybin',
    'loading': 'Loading...',
    'error': 'Error',
    'noInternet': 'No internet connection!',
    'retry': 'Retry',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'ok': 'OK',
    'submit': 'Submit',
    'update': 'Update',
    'done': 'Done',
    'skip': 'Skip',
    'description': 'Description',
    'settings': 'Settings',
    'search': 'Search...',
    'searchForEvents': 'Search for events',
    'searchForCommunities': 'Search for communities',
    'searchConversation': 'Search a conversation',
    'allVibes': 'All Vibes',
    'otherVibes': 'Other Vibes',
    'viewOnMap': 'View on Map',
    'create': 'Create',
    'expiresIn': 'Expires in',
    'expired': 'Expired',
    'lessThan1m': 'Less than 1m',
    'addNewCategory': 'Add New Category',
    'addSubCategory': 'Add Sub Category',
    'uploadCoverImage': 'Upload Cover Image',
    'clickToBrowse': 'Click to browse',
    'selectAddress': 'Select address',
    'select': 'Select',
    'eventDateTime': 'Event Date & Time',
    'startingDate': 'Starting Date',
    'startingTime': 'Starting Time',
    'endingDate': 'Ending Date',
    'endingTime': 'Ending Time',
    'selectedLocation': 'Selected Location',
    'privacyFirst': 'Privacy First',
    'privacyFirstDesc': 'Your exact location is only shared with people you wave to and accept',
    'organized': 'Organized',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'edit': 'Edit',
    'send': 'Send',
    'clear': 'Clear',
    'tapAgainToExit': 'Tap again to exit',
    'noItemsFound': 'No items found',
    'noResultsMatchSearch': 'No results match your search',
    'clearSearch': 'Clear search',
    'share': 'Share',
    'report': 'Report',
    'block': 'Block',
    'requestSent': 'Request sent',
    'invitationSent': 'Invitation sent',
    'processing': 'Processing...',
    'success': 'Success',
    'failed': 'Failed',
    'warning': 'Warning',
    'info': 'Info',
    'networkError': 'Network error. Try again.',
    'somethingWentWrong': 'Something went wrong. Try again',
    'pleaseWait': 'Please wait...',

    // ──── AUTH ────
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'signInToAccount': 'Sign in to your account',
    'createAccount': 'Create your account',
    'email': 'Email',
    'enterEmail': 'Enter your email',
    'password': 'Password',
    'enterPassword': 'Enter your password',
    'confirmPassword': 'Confirm Password',
    'name': 'Name',
    'enterName': 'Enter your name',
    'forgotPassword': 'Forgot Password?',
    'rememberMe': 'Remember me',
    'dontHaveAccount': "Don't have an account? ",
    'alreadyHaveAccount': 'Already have an account? ',
    'logOut': 'Log Out',
    'areYouSureLogOut': 'Are you sure you want to log out?',
    'otpVerification': 'OTP Verification',
    'verify': 'Verify',
    'resend': 'Resend',
    'resendCode': 'Resend Code',
    'resetPassword': 'Reset Password',
    'sendOtp': 'Send OTP',
    'congratulations': 'Congratulations!',
    'enterOtp': 'Enter the OTP sent to your email',
    'newPassword': 'New Password',
    'enterNewPassword': 'Enter new password',
    'passwordChanged': 'Password changed successfully',
    'accountCreated': 'Account created successfully',
    'otpVerified': 'OTP verified successfully.',
    'otpResent': 'OTP resent successfully',
    'loginSuccessful': 'Login successful',
    'emailSent': 'Email sent successfully',
    'emailVerification': 'Email Verification',
    'pleaseEnterEmail': 'Please enter your email',
    'pleaseEnterValidEmail': 'Please enter a valid email',
    'pleaseEnterPassword': 'Please enter your password',
    'passwordMinLength': 'Password must be at least 6 characters',
    'passwordsDoNotMatch': 'Passwords do not match',
    'preferNotToSay': 'Prefer not to say',
    'setPassword': 'Set Password',

    // ──── ONBOARDING / INTRO ────
    'getStarted': 'Get Started',
    'letsVibeTogether': "Let's vibe together",
    'discoverVibesDesc': 'Discover vibes happening around you',
    'spontaneousConnections': 'Make spontaneous real-life connections',
    'createOwnEvents': 'Create your own events',
    'createOwnCommunities': "Create your own communities",
    'safePrivacyFirst': 'Safe & privacy-first by design',
    'letsConnect': "Let's Connect",
    'continueText': 'Continue',
    'chooseLanguage': 'Choose Your Language',
    'selectPreferredLanguage': 'Select your preferred language',
    'stepName': 'What is your name?',
    'stepPhoto': 'Upload your photo',
    'stepInterests': 'Select your interests',
    'stepLocation': 'Set your location',
    'stepGender': 'Select your gender',
    'stepBirthday': 'When is your birthday?',
    'stepBirthdaySubtitle': 'Your profile will only show your age, never your full birth date.',
    'stepLookingFor': 'What are you looking for?',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'uploadPhoto': 'Upload Photo',
    'takePhoto': 'Take Photo',
    'chooseFromGallery': 'Choose from Gallery',
    'enterYourName': 'Enter your name',
    'selectInterests': 'Select your interests',
    'setLocation': 'Set Location',
    'currentLocation': 'Current Location',
    'welcomeTo': 'Welcome to Vybin',

    // ──── HOME ────
    'home': 'Home',
    'explore': 'Explore',
    'profile': 'Profile',
    'events': 'Events',
    'communities': 'Communities',
    'vibes': 'Vibes',
    'chat': 'Chat',
    'waves': 'Waves',
    'nearby': 'Nearby',
    'seeAll': 'See All',
    'discover': 'Discover',
    'map': 'Map',
    'filter': 'Filter',
    'all': 'All',
    'myEvents': 'My Events',
    'myCommunities': 'My Communities',
    'joined': 'Joined',
    'requested': 'Requested',
    'popular': 'Popular',
    'recent': 'Recent',
    'distance': 'Distance',
    'km': 'km',
    'mi': 'mi',
    'people': 'People',
    'attending': 'Attending',
    'interested': 'Interested',
    'maxAttendees': 'Max Attendees',
    'noEvents': 'No events found',
    'noCommunities': 'No communities found',
    'noVibes': 'No vibes available',

    // ──── EVENTS ────
    'createEvent': 'Create Event',
    'editEvent': 'Edit Event',
    'eventDetails': 'Event Details',
    'eventTitle': 'Event Title',
    'eventDate': 'Event Date',
    'eventTime': 'Event Time',
    'eventLocation': 'Event Location',
    'eventCategory': 'Category',
    'eventDescription': 'Description',
    'eventImage': 'Cover Image',
    'public': 'Public',
    'private': 'Private',
    'accessLevel': 'Access Level',
    'joinEvent': 'Join Event',
    'leaveEvent': 'Leave Event',
    'interestedEvent': 'Interested',
    'eventJoined': 'Joined successfully',
    'eventLeft': 'Left the event',
    'eventDeleted': 'Event deleted',
    'eventCreated': 'Event created',
    'eventUpdated': 'Event updated',
    'eventCheckin': 'Check In',
    'eventCheckout': 'Check Out',
    'eventMembers': 'Members',
    'eventRequests': 'Requests',
    'eventHost': 'Hosted by',
    'eventStart': 'Start',
    'eventEnd': 'End',
    'eventCapacity': 'Capacity',
    'eventFull': 'Event is full',
    'eventPrivate': 'This is a private event',
    'requestToJoin': 'Request to Join',
    'withdrawRequest': 'Withdraw Request',
    'scanQR': 'Scan QR Code',
    'showMyQR': 'Show My QR',
    'removeMember': 'Remove',
    'approve': 'Approve',
    'reject': 'Reject',
    'eventOrCommunity': 'What would you like to create?',

    // ──── COMMUNITIES ────
    'createCommunity': 'Create Community',
    'editCommunity': 'Edit Community',
    'communityDetails': 'Community Details',
    'communityTitle': 'Community Title',
    'communityDescription': 'Description',
    'communityRules': 'Rules',
    'communityLocation': 'Location',
    'communityDate': 'Date',
    'communityTime': 'Time',
    'communityCategory': 'Category',
    'communityImage': 'Cover Image',
    'joinCommunity': 'Join Community',
    'leaveCommunity': 'Leave Community',
    'interestedCommunity': 'Interested',
    'communityJoined': 'Joined successfully',
    'communityLeft': 'Left the community',
    'communityCreated': 'Community created',
    'communityUpdated': 'Community updated',
    'communityMembers': 'Members',
    'communityRequests': 'Requests',
    'manageMembers': 'Manage Members',
    'communityHost': 'Created by',
    'communityCapacity': 'Capacity',
    'communityFull': 'Community is full',
    'communityPrivate': 'This is a private community',
    'requestToJoinCommunity': 'Request to Join',
    'scheduleMeetup': 'Schedule Meetup',
    'meetups': 'Meetups',
    'createMeetup': 'Create Meetup',
    'meetupDetails': 'Meetup Details',
    'meetupTitle': 'Meetup Title',
    'meetupDescription': 'Description',
    'meetupDate': 'Meetup Date',
    'meetupTime': 'Meetup Time',
    'meetupLocation': 'Location',
    'meetupMembers': 'Meetup Members',
    'joinMeetup': 'Join Meetup',
    'meetupJoined': 'Joined meetup',
    'inviteMembers': 'Invite Members',
    'invited': 'Invited',
    'meetupCreated': 'Meetup created',
    'awaitingApproval': 'Awaiting Approval',
    'approved': 'Approved',

    // ──── CHAT ────
    'chats': 'Chats',
    'messages': 'Messages',
    'typeMessage': 'Type a message...',
    'sendMessage': 'Send',
    'voiceMessage': 'Voice Message',
    'image': 'Image',
    'photo': 'Photo',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'recordAudio': 'Record Audio',
    'stopRecording': 'Stop Recording',
    'deleteMessage': 'Delete Message',
    'editMessage': 'Edit Message',
    'copyMessage': 'Copy Message',
    'messageDeleted': 'This message was deleted',
    'messageEdited': '(edited)',
    'messageCopied': 'Copied',
    'areYouSureDelete': 'Are you sure you want to delete this message?',
    'noMessages': 'No messages yet',
    'isTyping': 'is typing...',
    'online': 'Online',
    'offline': 'Offline',
    'eventChat': 'Event Chat',
    'communityChat': 'Community Chat',
    'privateChat': 'Private Chat',
    'chatList': 'Chat List',
    'markAsRead': 'Mark as read',
    'unread': 'Unread',

    // ──── VIBE / WAVE ────
    'vibe': 'Vibe',
    'createVibe': 'Create Vibe',
    'myVibe': 'My Vibe',
    'vibeTitle': 'Vibe Title',
    'vibeDuration': 'Duration',
    'endVibe': 'End Vibe',
    'vibeEnded': 'Vibe ended',
    'vibeCreated': 'Vibe created',
    'sendWave': 'Send Wave',
    'waveSent': 'Wave sent!',
    'acceptWave': 'Accept',
    'rejectWave': 'Decline',
    'waveAccepted': 'Wave accepted!',
    'waveRejected': 'Wave declined',
    'incomingWave': 'Incoming Wave',
    'someoneWaved': 'Someone waved at you!',
    'waveFrom': 'Wave from',
    'meetConfirm': 'Confirm Meetup',
    'meetReschedule': 'Reschedule',
    'meetLocation': 'Suggest Location',
    'suggestedLocation': 'Suggested Location',
    'confirmMeetup': 'Confirm Meetup',
    'rescheduleMeetup': 'Reschedule Meetup',
    'meetNow': 'Meet Now',
    'activeVibes': 'Active Vibes',
    'noActiveVibes': 'No active vibes',

    // ──── PROFILE ────
    'myProfile': 'My Profile',
    'editProfile': 'Edit Profile',
    'profilePhoto': 'Profile Photo',
    'bio': 'Bio',
    'enterBio': 'Enter your bio',
    'interests': 'Interests',
    'changePassword': 'Change Password',
    'currentPassword': 'Current Password',
    'yourPhotos': 'Your Photos',
    'likedProfiles': 'Liked Profiles',
    'lockedProfile': 'Locked Profile',
    'profileLocked': 'This profile is locked',
    'unlockProfile': 'Unlock Profile',
    'trustScore': 'Trust Score',
    'meets': 'Meets',
    'lookingFor': 'Looking for',

    // ──── SETTINGS ────
    'language': 'Language',
    'english': 'English',
    'german': 'Deutsch',
    'theme': 'Theme',
    'light': 'Light',
    'dark': 'Dark',
    'system': 'System',
    'themeMode': 'Theme Mode',
    'notifications': 'Notifications',
    'privacy': 'Privacy',
    'termsOfService': 'Terms of Service',
    'privacyPolicy': 'Privacy Policy',
    'about': 'About',
    'version': 'Version',
    'account': 'Account',
    'deleteAccount': 'Delete Account',
    'areYouSureDeleteAccount': 'Are you sure you want to delete your account?',
    'deleteReason': 'Please tell us why you are leaving',
    'accountDeleted': 'Account deleted',
    'pauseProfile': 'Pause Profile',
    'profilePaused': 'Profile paused',
    'managePassword': 'Manage Password',
    'blockedAccounts': 'Blocked Accounts',
    'noBlockedAccounts': 'No blocked accounts',
    'help': 'Help',
    'appInfo': 'App Info',
    'logout': 'Logout',
    'loggedOut': 'Logged out successfully',

    // ──── SUBSCRIPTION ────
    'subscription': 'Subscription',
    'subscribe': 'Subscribe',
    'upgrade': 'Upgrade',
    'premium': 'Premium',
    'basic': 'Basic',
    'free': 'Free',
    'monthly': 'Monthly',
    'yearly': 'Yearly',
    'payment': 'Payment',
    'payNow': 'Pay Now',
    'paymentSuccessful': 'Payment Successful!',
    'paymentFailed': 'Payment failed',
    'choosePlan': 'Choose your plan',
    'currentPlan': 'Current Plan',

    // ──── QR ────
    'qrCode': 'QR Code',
    'scanQRCode': 'Scan QR Code',
    'myQRCode': 'My QR Code',
    'qrScan': 'Scan',
    'qrCodeFor': 'QR Code for',
    'scanToJoin': 'Scan to join',
    'invalidQR': 'Invalid QR code',
    'qrScanned': 'QR Code scanned',

    // ──── ADDITIONAL UI STRINGS ────
    'searchDot': 'Search ...',
    'youAreInsideEvent': 'You are inside the event',
    'enjoyTheMoment': 'Enjoy the moment!',
    'leaveEventZone': 'Leave Event Zone',
    'leftEventZone': 'Left Event Zone',
    'leftEventDesc': "You've left the Event Zone. Returning to the map...",
    'loadingEvent': 'Loading event...',
    'locationNotAvailable': 'Location not available',
    'eventZone': 'Event Zone',
    'eventNotFound': 'Event not found',
    'viewAll': 'View all',
    'noParticipants': 'No participants yet',
    'noPendingRequests': 'No pending requests',
    'noAwaitingMembers': 'No awaiting members',
    'accept': 'Accept',
    'participants': 'Participants',
    'manageRequest': 'Manage Request',
    'pending': 'Pending',
    'awaitingMeetup': 'Awaiting Meetup',
    'viewQR': 'View QR',
    'scanQRCodeToVerify': 'Scan QR Code',
    'aboutCommunity': 'About Community',
    'planedMeetup': 'Planned Meetup',
    'noMeetupsPlanned': 'No meetups planned yet',
    'planMeetup': 'Plan Meetup',
    'leave': 'Leave',
    'viewOnMapBtn': 'View on Map',
    'endVibeEarly': 'End Vibe Early?',
    'endVibeDesc': 'Your Vibe will disappear immediately from the map',
    'endNow': 'End Now',
    'noActiveVibe': 'No active vibe found.',
    'noOtherVibes': 'No other vibes found.',
    'vibeDurationLeft': 'left',
    'statusLive': 'LIVE',
    'noTitle': 'No Title',
    'waved': 'Waved',
    'wave': 'Wave',
    'itsAVibe': "It's a Vibe",
    'youBothWantToConnect': 'You both want to connect!',
    'suggestMeetingSpot': 'Suggest meeting spot',
    'cancelMeetup': 'Cancel Meetup',
    'greatSeeYouSoon': 'Great, see you soon!',
    'meetAtMyLocation': 'Meet at my location',
    'hereAndNow': 'Here and now',
    'suggestMidpoint': 'Suggest midpoint',
    'pickLocationOnMap': 'Pick location on map',
    'later': 'Later',
    'scheduleMeetupConfirm': 'Schedule a meetup to verify',
    'scheduleQRDesc': 'They need to scan your QR code to join the community.',
    'qrMustBeScanned': 'QR code must be scanned in person to become a member',
    'cancelMeetupAnytime': 'You can cancel this meetup anytime',
    'youreOfficialMember': "You're now an official member,",
    'feelFreeToSayHi': 'Feel free to say hi to the group',
    'enterCommunity': 'Enter Community',
    'members': 'Members',
    'pendingMeetupsNote': 'Pending meetups not completed may affect your Respect Score.',
    'trustEcosystem': 'This connects Communities with your Trust ecosystem.',
    'unblock': 'Unblock',
    'unblockSuccess': 'User unblocked successfully',
    'unblockFailed': 'Failed to unblock user. Please try again.',
    'areYouSureUnblock': 'Are you sure you want to unblock {userName}?',
    'whatHappened': 'What happened?',
    'blockDescription': 'Tell us why you want to block this user. They will not be notified.',
    'blockSuccess': 'You have blocked {userName}. You will not receive any notifications from this user.',
    'blockFailed': 'Failed to block user. Please try again.',
    'explainHere': 'Explain here...',
    'activeMembers': 'Active members',
    'invitedMembers': 'Invited members',
    'mute': 'Mute',
    'deleteChat': 'Delete Chat',
    'blockUser': 'Block User',
    'onlyCreatorCanSend': 'Only the event creator can send messages',
    'editingMessage': 'Editing message',
    'sentAFile': 'Sent a file',
    'addACaption': 'Add a caption...',
    'wantsToMeetYou': 'wants to meet you.',
    'acceptToSuggest': 'Accept to suggest a time and place for a quick meetup',
    'youHaveRejected': 'You have rejected',
    'waveRequest': 'wave request.',
    'youHaveReported': 'You have reported',
    'youWillNotReceive': 'You will not receive any notifications from this user.',
    'youHaveBlocked': 'You have blocked',
    'awaitingQR': 'Awaiting QR',
    'hasBeenApproved': 'has been approved!',
    'confirmPasswordToProceed': 'For security reasons, please confirm your password to proceed.',
    'giveReason': 'Give us a reason why you want to pause the account',
    'reason': 'Reason',
    'accountInformation': 'Account Information',
    'changeYourPassword': 'Change Your Password',
    'pauseYourAccount': 'Pause Your Account',
    'deleteYourAccount': 'Delete Your Account',
    'deleteConfirmation': 'Delete Confirmation',
    'deleteAccountDesc': 'You can delete your account, but please note the process may take some time to complete. Once deleted, it cannot be undone later.',
    'profileCompletion': 'Profile Completion',
    'selectUpTo5': 'Interests (select up to 5)',
    'max5Interests': 'You can select a maximum of 5 interests',
    'profileUpdated': 'Profile updated successfully',
    'passwordUpdated': 'Password updated successfully',
    'updatePassword': 'Update Password',
    'uploading': 'Updating...',
    'newCategory': 'Add New Category',
    'addCategory': 'Add',
    'enterCategoryName': 'Enter category name',
    'membersCount': 'Members (24)',
    'youAreAdmin': 'You are an Admin',
    'pendingMeetups': 'Pending meetups not completed may affect your Respect Score. This connects Communities with your Trust ecosystem.',
    'eventRequestSent': 'Event Request Sent',
    'yourRequestHasBeenSent': 'Your request has been sent!',
    'withdrawing': 'Withdrawing...',
    'eventAccessGranted': 'Event Access Granted',
    'qrCodeDescription': 'Remember to scan the QR code on arrival to check in',
    'createSomethingNew': 'Create something new',
    'startEventOrCommunity': 'Start an event or build a community.',
    'eventCategoryLabel': 'Event Category',
    'communityCategoryLabel': 'Community Category',
    'selectLocation': 'Select Location',
    'profileCompletionLabel': 'Profile Completion',
    'noBioYet': 'No bio yet',
    'locationNotSet': 'Location not set',
    'enterYourBio': 'Enter your bio here. It will be visible to your friends',
    'addInterestCategory': 'Add Interest Category',
    'enterInterestName': 'Enter interest name',
    'addSubInterest': 'Add Sub Interest',
    'areYouSureDeletePhoto': 'Are you sure you want to delete this photo?',
    'photoAdded': 'Photo added successfully',
    'failedToUpload': 'Failed to upload photo. Please try again.',
    'profilePhotoUpdated': 'Profile photo updated',
    'failedToUpdatePhoto': 'Failed to update profile photo. Please try again.',
    'changePhoto': 'Change',
    'failedToPickImage': 'Failed to pick image',
    'updateEvent': 'Update',
    'updateEventConfirm': 'Updating it will notify all meeting participants.\nAre you sure?',
    'deleteEventConfirm': 'Are you sure you want to Delete it?',
    'archiveConfirm': 'Are you sure you want to Archive it?',
    'yes': 'Yes',
    'youDeletedEvent': 'You deleted the event',
    'communityInfo': 'Community info',
    'selectDateAndTimeFirst': 'Select date and time first',
    'noParticipantsYet': 'No participants yet',
    'noInvitedMembers': 'No invited members yet',
    'noMembersFound': 'No members found',
    'photoAddedSuccess': 'Photo added successfully',
    'updating': 'Updating...',
    'invalidCommunity': 'Invalid community',
    'communityUpdatedSuccess': 'Community updated successfully',
    'failedToUpdateCommunity': 'Failed to update community',
    'sundayCoffeeVibes': 'Sunday Coffee Vibes',
    'termsAndPrivacy': 'Terms and Privacy',
    'passwordMinLengthError': 'Password must be at least 6 characters',
    'passwordsDoNotMatchError': 'Passwords do not match',

    // ──── NEW KEYS ────
    'defaultUserName': 'User',
    'myLocation': 'My Location',
    'scanChatQR': 'Scan a chat QR code to connect',
    'scanCommunityQR': 'Scan a community QR code to join',
    'scanEventQR': 'Scan event QR code to check in',
    'scanName': 'Scan',
    'paymentMethod': 'Payment Method',
    'paypal': 'PayPal',
    'stripe': 'Stripe',
    'yourPaymentSuccessful': 'Your payment has been successfully done',
    'upgradePlan': 'Upgrade plan',
    'mostPopular': 'Most Popular',
    'perMonth': '/month',
    'selectMonth': 'Select month',
    'subscriptionFree': 'Free',
    'plans': 'Plans',
    'getStartedWithLocalDiscovery': 'Get started with local discovery',
    'forActiveMembers': 'For active community members',
    'forOrganizers': 'For organizers and power users',
    'private_tab': 'Private',
    'wavesPerDay': 'Waves / day',
    'unlimitedVibes': 'Unlimited vibes',
    'joinUpTo': 'Join up to',
    'communitiesCount': 'communities',
    'createUpTo': 'Create up to',
    'membersPerCommunity': 'members / community',
    'eventsPerMonth': 'events / month',
    'participantsPerEvent': 'participants / event',
    'wavedAt': 'Waved at',
    'unlimitedWaves': 'Unlimited Waves',
    'unlimitedCommunities': 'Unlimited communities',
    'createUpToCommunities': 'Create up to',
    'unlimitedMembers': 'Unlimited members',
    'joinEventsNoLimit': 'Join events without distance limits',
    'createUnlimitedEvents': 'Create unlimited events',
    'unlimitedParticipants': 'Unlimited participants',
    'maxImages': 'Maximum images allowed',
    'reportSpam': 'Spam or Misinformation',
    'reportHateSpeech': 'Hate Speech or Violence',
    'reportThreats': 'Threats or Harassment',
    'reportHint': 'Give a brief description ...',
    'others': 'Others',
    'proTip': 'Pro Tip',
    'gotIt': 'Got it!',
    'eventOption': 'Event',
    'communityOption': 'Community',
    'eventOptionDesc': 'Organize gatherings, meetups, or special occasions that bring people together',
    'communityOptionDesc': 'Build a space where people with shared interests can connect and grow together',
    'proTipDesc': 'Communities are for long-term connections, Events are for specific occasions, and Vibes are for capturing fleeting moments.',

    // ──── TIME / DATE ────
    'jan': 'Jan',
    'feb': 'Feb',
    'mar': 'Mar',
    'apr': 'Apr',
    'may': 'May',
    'jun': 'Jun',
    'jul': 'Jul',
    'aug': 'Aug',
    'sep': 'Sep',
    'oct': 'Oct',
    'nov': 'Nov',
    'dec': 'Dec',
    'justNow': 'just now',
    'minAgo': 'min ago',
    'hourAgo': 'hour ago',
    'hoursAgo': 'hours ago',
    'yesterday': 'yesterday',
    'am': 'AM',
    'pm': 'PM',

    // ──── COMMUNITY MEMBER SCREEN ────
    'activeTab': 'Active',
    'requestedTab': 'Requested',
    'manage': 'Manage',
    'noActiveMembers': 'No active members yet',
    'requestedToJoin': 'Requested to join',
    'youHaveAcceptedJoinRequest': 'You have accepted ',
    'youHaveRejectedJoinRequest': 'You have rejected ',
    'sJoinRequest': "'s community join request.",
    'sJoinRequestRejected': "'s community join request.",
    'failedToAccept': 'Failed to accept request.',
    'failedToReject': 'Failed to reject request.',

    // ──── MEETUP MEMBER SCREEN ────
    'participantsTab': 'Participants',
    'invitedTab': 'Invited',
    'unknown': 'Unknown',
    'joinedAgo': 'Joined ',
    'invitedAgo': 'Invited ',

    // ──── PLAN FEATURES ────
    'planFreeWaveCount': '6 Waves / day',
    'planFreeUnlimitedVibes': 'Unlimited vibes',
    'planFreeJoinCommunities': 'Join up to 3 communities',
    'planFreeCreateCommunity': 'Create 1 community',
    'planFreeMembersPerCommunity': 'Up to 25 members / community',
    'planFreeEventRange': 'Join events within 200 km',
    'planFreeCreateEvent': 'Create 1 event / month',
    'planPlusWaveCount': '12 Waves / day',
    'planPlusUnlimitedVibes': 'Unlimited Vibes',
    'planPlusJoinCommunities': 'Join up to 6 communities',
    'planPlusCreateCommunities': 'Create up to 3 communities',
    'planPlusMembersPerCommunity': 'Up to 50 members / community',
    'planPlusCreateEvents': 'Create 4 events / month',
    'planPlusParticipantsPerEvent': 'Up to 100 participants / event',
    'planPremiumUnlimitedWaves': 'Unlimited Waves',
    'planPremiumUnlimitedVibes': 'Unlimited Vibes',
    'planPremiumJoinUnlimitedCommunities': 'Join unlimited communities',
    'planPremiumCreateCommunities': 'Create up to 6 communities',
    'planPremiumUnlimitedMembers': 'Unlimited members / community',
    'planPremiumJoinEventsNoLimit': 'Join events without distance limits',
    'planPremiumCreateUnlimitedEvents': 'Create unlimited events',
    'planPremiumUnlimitedParticipants': 'Unlimited participants / event',

    // ──── INTERESTS ────
    'interestCoffee': 'Coffee',
    'interestMusic': 'Music',
    'interestBooks': 'Books',
    'interestGaming': 'Gaming',
    'interestCalendar': 'Calendar',
    'interestTravel': 'Travel',
    'interestFitness': 'Fitness',
    'interestCooking': 'Cooking',
    'interestArt': 'Art',
    'interestPhotography': 'Photography',

    // ──── PROFILE ────
    'defaultBio': 'Coffee enthusiast. Music lover. Avid traveler. Foodie.',

    // ──── MISSING KEYS ────
    'youLeft': 'You left ',
    'going': 'going',

    // ──── SETTINGS SCREEN ────
    'locationSharing': 'Location Sharing',
    'locationSharingDesc': 'Only active during vibes',
    'blocked': 'Blocked',
    'appSetting': 'App setting',
    'community': 'Community',

    // ──── LOCALIZATION GAPS ────
    'away': 'away',
    'notNow': 'Not Now',
    'allow': 'Allow',
    'locationAccess': 'Location access',
    'locationAccessDesc': 'Used to connect you with what’s nearby.',
    'locationAccessSubtitle': 'Only while using the app.',
    'sendInvitation': 'Send Invitation',
    'inviteMembersToMeetup': 'Invite members to meetup plan',
    'selectedMembersWillReceive': 'Selected members will receive an invitation to join for the event',
    'invitedAll': 'Invited All',
    'member': 'Member',
    'awaiting': 'Awaiting',
    'scheduledMeetup': 'Scheduled Meetup',
    'location': 'Location',
    'statusPendingApproval': 'Status: Pending approval',
    'invitedToRealLifeMeetup': 'You\'ll be invited to a real-life meetup before becoming a member.',
    'youJoinedTheMeetup': 'You\'ve joined the meetup!',
    'communityNotifications': 'Community Notifications',
    'event_tab': 'Event',
    'eventNotifications': 'Event Notifications',
    'qrVerification': 'QR Verification',
    'qrTab': 'QR Code',
    'scanTab': 'Scan',
    'scanTheirQRCode': 'Scan Their QR Code',
    'alignQRCode': 'Align the QR code in the frame',
    'cameraPermissionRequired': 'Camera permission required',
    'uniqueQRCode': 'This code is unique for this connection',
    'qrInfoCommunity': 'Scan this QR code to join a community or connect with other members.',
    'qrInfoEvent': 'Scan this QR code for event access or verification.',
    'qrInfoChats': 'Scan this QR code to create a direct personal connection.',
    'qrTitleCommunity': 'Join a Community',
    'qrTitleEvent': 'Event Access & Verification',
    'qrTitleChats': 'Connect with Chats',
    'qrSubtitleCommunity': 'Let others scan this code to join the community',
    'qrSubtitleEvent': 'Present this code for event entry or verification',
    'qrSubtitleChats': 'Let them scan to connect with you instantly',
    'qrScanCommunity': 'Scan the QR code to join the community and start connecting.',
    'qrScanEvent': 'Scan the QR code to securely access the event.',
    'qrScanChats': 'Scan the QR code to connect instantly through chat.',
    'history': 'History',
    'clearAll': 'Clear All',
    'eventPublicDesc': 'Anyone can discover and join this event instantly without approval.',
    'eventPrivateDesc': 'People will need your approval before they can join this event.',
    'respectScore': 'Respect Score',
    'trusted': 'Trusted',
    'noRealLifeMeets': 'No real-life meets yet',
    'basedOnMeets': 'Based on ',
    'realLifeMeets': 'real-life meets',
    'youHaveAcceptedRequestDesc': 'You have accepted the community join request.',

    // ──── BLOCKED CHAT ────
    'youBlockedThisUser': 'You blocked this user. Unblock to send messages.',
    'youHaveBeenBlocked': 'You have been blocked by this user.',
  };
}
